ktor:
  deployment:
    port: ${?PORT}
  application:
    modules:
      - dev.avadhut.wist.ApplicationKt.module

firecrawl:
  apiKey: ${?FIRECRAWL_API_KEY}
  baseUrl: "https://api.firecrawl.dev"

jwt:
  secret: ${?JWT_SECRET}
  issuer: "wist-server"
  audience: "wist-users"

db:
  driver: "org.postgresql.Driver"
  url: ${?DB_URL}
  user: ${?DB_USER}
  password: ${?DB_PASSWORD}
